prefix public: <http://rdf.basekb.com/public/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix vrank: <http://purl.org/voc/vrank#>
prefix dbpedia: <http://dbpedia.org/resource/>

select (count(?s) as ?cnt) {
   ?s public:subjectiveEye3D ?eye .
   ?s vrank:hasRank/vrank:rankValue ?pr .
}